[package]
name = "cursorup"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.22", features=["json"] }
serde = { version = "1.0.219", features=["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.46.1", features=["rt-multi-thread", "macros", "fs", "process"]}
